const Detail =[
    {
        id: 1,
        Title: "product a", 
        Price: 400,
        Img: "./Images/shoe10.jpg",
        Name: "block heel",
    },
    {
        id: 2,
        Title: "product b", 
        Price: 950,
        Img: "./Images/shoe13.jpg",
        Name: "short heel",
    },
    {
        id: 3,
        Title: "product c", 
        Price: 200,
        Img: "./Images/shoe12.jpg",
        Name: "Flat heel",
    },
    {
        id: 4,
        Title: "product d", 
        Price: 700,
        Img: "./Images/shoe11.jpg",
        Name: "high heel",
    },
    {
        id: 5,
        Title: "product e", 
        Price: 1000,
        Img: "./Images/shoe14.jpg",
        Name: "white sneaker",
    },
    {
        id: 6,
        Title: "product f", 
        Price: 850,
        Img: "./Images/shoe1.jpg",
        Name: "black sneaker",
    },
    {
        id: 7,
        Title: "product g", 
        Price: 400,
        Img: "./Images/shoe16.jpg",
        Name: "multi-colored sneaker",
    },
    {
        id: 8,
        Title: "product h", 
        Price: 650,
        Img: "./Images/shoe15.jpg",
        Name: "red sneaker",
    },
    {
        id: 9,
        Title: "product i", 
        Price: 517,
        Img: "./Images/shoe20.jpg",
        Name: "red-colored sneaker",
    },
    {
        id: 10,
        Title: "product j", 
        Price: 318,
        Img: "./Images/shoe18.jpg",
        Name: "grey-colored sneaker",
    },
    {
        id: 11,
        Title: "product k", 
        Price: 600,
        Img: "./Images/shoe19.jpg",
        Name: "black-colored sneaker",
    },
    {
        id: 12,
        Title: "product l", 
        Price: 258,
        Img: "./Images/shoe17.jpg",
        Name: "blue-colored sneaker",
    },
    {
        id: 13,
        Title: "product m", 
        Price: 650,
        Img: "./Images/shoe7.jpg",
        Name: "white & red sneaker",
    },
    {
        id: 14,
        Title: "product n", 
        Price: 300,
        Img: "./Images/shoe5.jpg",
        Name: "black & white sneaker",
    },
    {
        id: 15,
        Title: "product o", 
        Price: 650,
        Img: "./Images/shoe7.jpg",
        Name: "white & red sneaker",
    },
    {
        id: 16,
        Title: "product p", 
        Price: 300,
        Img: "./Images/shoe5.jpg",
        Name: "black & white sneaker",
    },
]

export default Detail
